SELECT
    date,
    SUM(add_to_cart) AS add_to_cart,
    SUM(clicks) AS clicks,
    NULL AS comments, 
    --SUM(clicks + video_views) AS engagements,
    NULL AS engagements,
    SUM(impressions) AS impressions,
    SUM(rt_installs) AS installs,
    NULL AS likes,
    NULL AS link_clicks,
    NULL AS post_click_conversions,
    NULL AS post_view_conversions,
    NULL AS posts,
    SUM(purchase) AS purchase,
    SUM(registrations) AS registrations,
    NULL AS revenue,
    NULL AS shares,
    SUM(spend) AS spend,
    SUM(conversions) AS total_conversions,
    NULL AS video_views,
    ad_id,
    NULL AS adset_id,
    campaign_id,
    channel,
    NULL AS creative_id,
    NULL AS placement_id
FROM {{ ref('src_ads_tiktok_ads_all_data') }}
GROUP BY 
    date,
    ad_id,
    adset_id,
    campaign_id,
    channel,
    creative_id,
    placement_id